SET C51INC=C:\ProgramFiles2\Keil_v5\C51\Inc
SET C51LIB=C:\ProgramFiles2\Keil_v5\C51\Lib
SET CPU_TYPE=M8051EW
SET CPU_VENDOR=Mentor Graphics Co.
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00B71B00
"C:\ProgramFiles2\Keil_v5\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\app_main.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\boot.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\bt_mode.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\Flash.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\key.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\main.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\rgb.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\uart.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\update.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\voice_ic.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\WIFI_M~1.__I"
"C:\ProgramFiles2\Keil_v5\C51\BIN\C51.EXE" @".\Objects\PWM.__i"
"C:\ProgramFiles2\Keil_v5\C51\BIN\BL51.EXE" @".\Objects\GP389.lnp"
"C:\ProgramFiles2\Keil_v5\C51\BIN\OH51.EXE" ".\Objects\GP389" 
